name: your_cooked
description: "Interview prep"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  firebase_ai: ^3.0.0
  firebase_database: ^12.0.0
  cloud_firestore: ^6.0.0
  google_sign_in: ^7.0.0

  # Navigation
  go_router: ^16.0.0

  # UI
  flex_color_scheme: ^8.2.0
  gap: ^3.0.1
  textfield_tags: ^3.0.1
  flutter_profile_picture: ^2.0.0
  percent_indicator: ^4.2.5
  fl_chart: ^1.0.0
  intl: ^0.20.2

  # State Management & Utilities
  result_dart: ^2.1.1
  collection: ^1.19.1
  freezed: 3.1.0
  freezed_annotation: ^3.1.0

  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  firebase_app_check: ^0.4.0
  algolia_helper_flutter: ^1.2.1
  infinite_scroll_pagination: ^5.1.0
  skeletonizer: ^2.1.0+1
  firebase_crashlytics: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linters & Code Generation
  flutter_lints: ^6.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.6.5


  mockito: ^5.4.0

flutter:
  uses-material-design: true
