// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0CnPYcnKZytnp8wrqGGyd1jMFqZc_DVU',
    appId: '1:661306578439:web:db97527822a47bef00bca2',
    messagingSenderId: '661306578439',
    projectId: 'your-cooked',
    authDomain: 'your-cooked.firebaseapp.com',
    databaseURL: 'https://your-cooked-default-rtdb.firebaseio.com',
    storageBucket: 'your-cooked.firebasestorage.app',
    measurementId: 'G-NNVJM1VJ2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaeiz-VtiX6v7yZVbU15m8wWVrEakCsbE',
    appId: '1:661306578439:android:8ff581dfbcca8ce300bca2',
    messagingSenderId: '661306578439',
    projectId: 'your-cooked',
    databaseURL: 'https://your-cooked-default-rtdb.firebaseio.com',
    storageBucket: 'your-cooked.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPa0nYHrLm-mQIDMKJaTQJeB-U250SqpQ',
    appId: '1:661306578439:ios:21b3db59ec10b41800bca2',
    messagingSenderId: '661306578439',
    projectId: 'your-cooked',
    databaseURL: 'https://your-cooked-default-rtdb.firebaseio.com',
    storageBucket: 'your-cooked.firebasestorage.app',
    iosClientId:
        '661306578439-4fjooq13qmld1u9f1k4ng8p9mraibc6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourCooked',
  );
}
